# Generated by Django 2.1.7 on 2019-07-19 15:19

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iletisim_adsoyad', models.CharField(max_length=100, verbose_name='Gönderenin Ad-Soyadı')),
                ('iletisim_telefon', models.CharField(max_length=100, verbose_name='Ulaşım Bilgileri')),
                ('iletisim_mail', models.CharField(max_length=100, verbose_name='Mail Adresi')),
                ('iletisim_mesaj', models.TextField(verbose_name='Mesaj')),
                ('iletisim_tarihi', models.DateTimeField(auto_now_add=True, verbose_name='İletişim Formu Gönderilme Tarihi')),
            ],
            options={
                'verbose_name': 'İletişim Talebi',
                'verbose_name_plural': 'İletişim Talepleri',
                'ordering': ('-iletisim_tarihi',),
            },
        ),
        migrations.CreateModel(
            name='Makaleler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_baslik', models.CharField(max_length=150, verbose_name='Makale Başlığı')),
                ('makale_yayintarihi', models.DateField(verbose_name='Makale Yayın Tarihi')),
                ('makale_mesaj', ckeditor.fields.RichTextField()),
                ('makale_slug', models.SlugField(unique=True)),
                ('makale_kategori', models.CharField(choices=[('ishukuku', 'İş Hukuku'), ('icrahukuku', 'İcra Hukuku'), ('ailehukuku', 'Aile Hukuku'), ('ticarethukuku', 'Ticaret Hukuku'), ('sigortahukuku', 'Sigorta Hukuku'), ('saglikhukuku', 'Sağlık Hukuku'), ('gayrimenkulhukuku', 'Gayrimenkul Hukuku'), ('sozlesmelerhukuku', 'Sözleşmeler Hukuku'), ('cezahukuku', 'Ceza Hukuku')], max_length=50, verbose_name='Makale Kategorisi')),
                ('makale_meta_description', models.CharField(max_length=350, verbose_name='Makale Meta Açıklaması(SEO İÇİN)')),
            ],
            options={
                'verbose_name': 'Makale',
                'verbose_name_plural': 'Makaleler',
                'ordering': ('-makale_yayintarihi',),
            },
        ),
        migrations.CreateModel(
            name='MakaleTags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('makale_tag_isim', models.CharField(max_length=100, verbose_name='Makale Tag')),
            ],
            options={
                'verbose_name': 'Makale Etiketi',
                'verbose_name_plural': 'Makale Etiketleri',
            },
        ),
        migrations.AddField(
            model_name='makaleler',
            name='tag',
            field=models.ManyToManyField(to='mainapp.MakaleTags'),
        ),
    ]
